
version: "3.8"
services:
  mongo:
    image: mongo:3.6.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../data/mongo:/data/db
    command: --master
#networks:
#  default:
#    external:
#      name: backend

#services:
#  mymoviedb:
#    image: mongo:latest
#    container_name: mymoviedb
#    ports:
#      - 27017:27017
#  movie-app-image:
#    image: movie-app-image
#    container_name: movie-app-image
#    ports:
#      - 8080:8080
#    links:
#      - mymoviedb